/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DonorAdmin;

import Business.DonorSystem.Donor;
import Business.DonorSystem.DonorDirectory;
import Business.EcoSystem;
import Business.Person;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.jdbcConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Logger;

/**
 *
 * @author kashr
 */
public final class DonorAdminJPanel extends javax.swing.JPanel {
    
    EcoSystem system;
    String DonorAdminID;
    JPanel container;

    /**
     * Creates new form DonorAdminJPanel
     */
    public DonorAdminJPanel(JPanel _container, EcoSystem _business, String _DonorID) {
        initComponents();
        System.out.print("Donor admin logged in");
        this.system = _business;
        this.DonorAdminID = _DonorID;
        this.container = _container;
        populateTable();
    }
    
    public void populateTable(){  
        System.out.print("Tryna populate \n");
        DonorDirectory donorDir = system.getDonorList();
        DefaultTableModel model = (DefaultTableModel) tblDonor.getModel();
        model.setRowCount(0);                
        donorDir.getDirectory().stream().map(item -> {
            Object[] row = new Object[5];
            row[0] = item.getName();
            row[1] = item.getUniqueID();
            row[2] = item.getBloodGroup();
            row[3] = item.getAge();
            return row;
        }).forEachOrdered(row -> {
            model.addRow(row);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonor = new javax.swing.JTable();
        btnUpdateDonor = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtdonorName = new javax.swing.JTextField();
        txtdonorEmail = new javax.swing.JTextField();
        txtdonorContact = new javax.swing.JTextField();
        txtdonorAddress = new javax.swing.JTextField();
        txtdonorCity = new javax.swing.JTextField();
        txtdonorBloodGrp = new javax.swing.JTextField();
        btnDeleteDonor = new javax.swing.JButton();
        btnAddNewDonor = new javax.swing.JButton();
        lblage = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblage1 = new javax.swing.JLabel();
        isAvailablejCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Donor List");

        tblDonor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Insurance Number", "Blood Group", "Age"
            }
        ));
        tblDonor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDonor);

        btnUpdateDonor.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdateDonor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnUpdateDonor.setText("Update");
        btnUpdateDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDonorActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NAME");

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMAIL ID");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CONTACT");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADDRESS");

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CITY");

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("BLOOD GROUP");

        txtdonorEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdonorEmailActionPerformed(evt);
            }
        });

        btnDeleteDonor.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteDonor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnDeleteDonor.setText("Delete");
        btnDeleteDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDonorActionPerformed(evt);
            }
        });

        btnAddNewDonor.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewDonor.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnAddNewDonor.setText("Add New");
        btnAddNewDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDonorActionPerformed(evt);
            }
        });

        lblage.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        lblage.setForeground(new java.awt.Color(255, 255, 255));
        lblage.setText("AGE");

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblage1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        lblage1.setForeground(new java.awt.Color(255, 255, 255));
        lblage1.setText("AVAILABLE FOR ORGAN DONATION");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/donor-care-network-link-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(btnDeleteDonor)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnUpdateDonor)
                                        .addGap(40, 40, 40)
                                        .addComponent(btnAddNewDonor))
                                    .addComponent(txtdonorBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblage1)
                                .addGap(32, 32, 32)
                                .addComponent(isAvailablejCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdonorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdonorName))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdonorCity))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdonorAddress))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtdonorContact)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdonorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdonorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdonorContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdonorAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdonorCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdonorBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblage1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isAvailablejCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDonor)
                    .addComponent(btnUpdateDonor)
                    .addComponent(btnAddNewDonor))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDonorActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex= tblDonor.getSelectedRow();
        
       if(selectedRowIndex<0){            
            return;
       }
       DefaultTableModel model= (DefaultTableModel) tblDonor.getModel();
       String insuranceNumber= (String) model.getValueAt(selectedRowIndex, 1);
       
       Donor donor = system.getDonor(insuranceNumber);
       if(isAvailablejCheckBox.isSelected()==true)
       { donor.organDonationStatus(insuranceNumber);
      
       }
       String donorName = txtdonorName.getText();
       donor.setName(donorName);
       
       String donorContact = txtdonorContact.getText();
       donor.setPhoneNumber(donorContact);
       
       String address = txtdonorAddress.getText();
       donor.setAddress(address);
       
       String email = txtdonorEmail.getText();
       donor.setEmail(email);
       
       String city = txtdonorCity.getText();
       donor.setCity(city);
       
       int age = Integer.parseInt(txtAge.getText());
       donor.setAge(age);
       
       system.updateDonor(donor);
       populateTable();
    }//GEN-LAST:event_btnUpdateDonorActionPerformed

    private void btnDeleteDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDonorActionPerformed
        // TODO add your handling code here:
        deleteDonor();
    }//GEN-LAST:event_btnDeleteDonorActionPerformed

    private void btnAddNewDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDonorActionPerformed
        // TODO add your handling code here:
        DonorCreateJPanel donorCreatePanel = new DonorCreateJPanel(container, system, DonorAdminID);
        container.add("donorCreatePanel", donorCreatePanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);    
    }//GEN-LAST:event_btnAddNewDonorActionPerformed

    private void txtdonorEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdonorEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdonorEmailActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void tblDonorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonorMouseClicked
        // TODO add your handling code here:
      int selectedRowIndex= tblDonor.getSelectedRow();
        
       if(selectedRowIndex<0){            
            return;
       }
       DefaultTableModel model= (DefaultTableModel) tblDonor.getModel();
       String insuranceNumber= (String) model.getValueAt(selectedRowIndex, 1);
       
       Donor donor = system.getDonor(insuranceNumber);
       
       txtdonorName.setText(donor.getName());
       txtdonorEmail.setText(donor.getEmail());
       txtdonorAddress.setText(donor.getAddress());
       txtdonorCity.setText(donor.getCity());
       txtdonorBloodGrp.setText(donor.getBloodGroup());
       txtdonorContact.setText(donor.getPhoneNumber());
       txtAge.setText(Integer.toString(donor.getAge()));
       isAvailablejCheckBox.setSelected(donor.isIsOrganDonor());
    }//GEN-LAST:event_tblDonorMouseClicked
    
    
    public void deleteDonor()
    { 
        jdbcConnection dbconn = system.getConnection();
        Connection conn = dbconn.connect();        
        String sql = "DELETE FROM donorTable where insuranceNumber=?";
        try {
        DefaultTableModel model = (DefaultTableModel) tblDonor.getModel();
        PreparedStatement pstmt = conn.prepareStatement(sql);
        int row_val = tblDonor.getSelectedRow();
        String insuranceNumber= (String) model.getValueAt(row_val, 1);
        pstmt.setString(1,insuranceNumber);
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(container, "The Donor has been deleted successfully");
        populateTable();
        } catch (SQLException ex) {
            Logger.getLogger(jdbcConnection.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(container, "An error has occured while deleting a donor");
        }
            finally
            {
                dbconn.disConnnect(conn);
            }



    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDonor;
    private javax.swing.JButton btnDeleteDonor;
    private javax.swing.JButton btnUpdateDonor;
    private javax.swing.JCheckBox isAvailablejCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblage1;
    private javax.swing.JTable tblDonor;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtdonorAddress;
    private javax.swing.JTextField txtdonorBloodGrp;
    private javax.swing.JTextField txtdonorCity;
    private javax.swing.JTextField txtdonorContact;
    private javax.swing.JTextField txtdonorEmail;
    private javax.swing.JTextField txtdonorName;
    // End of variables declaration//GEN-END:variables
}
