/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.OrganResearch;

import Business.EcoSystem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.jdbcConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import ui.Sysadmin.HospitalManagementJPanel;
import Business.OrganBankResearcher.OrganBankResearcherDirectory;
import ui.BloodBank.CreateBloodResearcherJPanel;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import Business.OrganBankResearcher.OrganBankResearcher;
import javax.swing.JOptionPane;




/**
 *
 * @author ABHI
 */
public class OrganBankAdminJPanel extends javax.swing.JPanel {
    
    String DonorAdminID;
    JPanel container;
     EcoSystem business;
    /**
     * Creates new form BloodBankAdminJPanel
     */
    public OrganBankAdminJPanel(JPanel _container,EcoSystem _business ,String _DonorID) {
        initComponents();
       this.business = _business;
        this.DonorAdminID = _DonorID;
        this.container = _container;
       // JOptionPane.showMessageDialog(container, DonorAdminID);
        jdbcConnection jdbcconnect = new jdbcConnection();
        Connection conn =jdbcconnect.connect();
        initalizeOrganBank(DonorAdminID);
        OrganBankResearcherDirectory directory = new OrganBankResearcherDirectory();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         
        TableModel table = directory.getOrganBankResearcherDirectory(DonorAdminID);
        jTable1.setModel(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        IdjLabel = new javax.swing.JLabel();
        AgejLabel = new javax.swing.JLabel();
        addAgejTextField = new javax.swing.JTextField();
        AddressjLabel = new javax.swing.JLabel();
        AddressjTextField = new javax.swing.JTextField();
        phoneNumberjTextField = new javax.swing.JTextField();
        PhoneNumberjLabel = new javax.swing.JLabel();
        PhoneNumberjLabel1 = new javax.swing.JLabel();
        addUserNamejTextField = new javax.swing.JTextField();
        addPasswordjTextField = new javax.swing.JTextField();
        PhoneNumberjLabel2 = new javax.swing.JLabel();
        AddressjLabel1 = new javax.swing.JLabel();
        zipCodejTextField = new javax.swing.JTextField();
        AddressjLabel2 = new javax.swing.JLabel();
        CityjTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        NamejLabel1 = new javax.swing.JLabel();
        addNamejTextField = new javax.swing.JTextField();
        NamejLabel2 = new javax.swing.JLabel();
        NamejLabel3 = new javax.swing.JLabel();
        addNamejTextField1 = new javax.swing.JTextField();
        AgejLabel1 = new javax.swing.JLabel();
        addAgejTextField1 = new javax.swing.JTextField();
        AddressjLabel3 = new javax.swing.JLabel();
        AddressjTextField1 = new javax.swing.JTextField();
        AddressjLabel4 = new javax.swing.JLabel();
        zipCodejTextField1 = new javax.swing.JTextField();
        AddressjLabel5 = new javax.swing.JLabel();
        CityjTextField1 = new javax.swing.JTextField();
        PhoneNumberjLabel3 = new javax.swing.JLabel();
        phoneNumberjTextField1 = new javax.swing.JTextField();
        PhoneNumberjLabel4 = new javax.swing.JLabel();
        addUserNamejTextField1 = new javax.swing.JTextField();
        PhoneNumberjLabel5 = new javax.swing.JLabel();
        addPasswordjTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        NamejLabel4 = new javax.swing.JLabel();
        IdjLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Add Researcher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Age", "Address", "ZipCode", "City", "Phone Number", "Organ Bank ID", "Work Assigned", "personId"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Update Researcher Information");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        IdjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IdjLabel.setForeground(new java.awt.Color(255, 255, 255));
        IdjLabel.setText("Id");

        AgejLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgejLabel.setForeground(new java.awt.Color(255, 255, 255));
        AgejLabel.setText("Age");

        AddressjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressjLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddressjLabel.setText("Address");

        AddressjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextFieldActionPerformed(evt);
            }
        });

        PhoneNumberjLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberjLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberjLabel.setText("Phone Number");

        PhoneNumberjLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberjLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberjLabel1.setText("User Name");

        addUserNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserNamejTextFieldActionPerformed(evt);
            }
        });

        addPasswordjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordjTextFieldActionPerformed(evt);
            }
        });

        PhoneNumberjLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberjLabel2.setText("Password");

        AddressjLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressjLabel1.setForeground(new java.awt.Color(255, 255, 255));
        AddressjLabel1.setText("ZipCode");

        zipCodejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodejTextFieldActionPerformed(evt);
            }
        });

        AddressjLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        AddressjLabel2.setText("City");

        CityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityjTextFieldActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Update ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        NamejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamejLabel1.setForeground(new java.awt.Color(255, 255, 255));
        NamejLabel1.setText("Name");

        NamejLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamejLabel2.setForeground(new java.awt.Color(255, 255, 255));
        NamejLabel2.setText("Researcher Id");

        NamejLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamejLabel3.setForeground(new java.awt.Color(255, 255, 255));
        NamejLabel3.setText("Name");

        AgejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AgejLabel1.setForeground(new java.awt.Color(255, 255, 255));
        AgejLabel1.setText("Age");

        AddressjLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressjLabel3.setForeground(new java.awt.Color(255, 255, 255));
        AddressjLabel3.setText("Address");

        AddressjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressjTextField1ActionPerformed(evt);
            }
        });

        AddressjLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressjLabel4.setForeground(new java.awt.Color(255, 255, 255));
        AddressjLabel4.setText("ZipCode");

        zipCodejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodejTextField1ActionPerformed(evt);
            }
        });

        AddressjLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressjLabel5.setForeground(new java.awt.Color(255, 255, 255));
        AddressjLabel5.setText("City");

        CityjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityjTextField1ActionPerformed(evt);
            }
        });

        PhoneNumberjLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberjLabel3.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberjLabel3.setText("Phone Number");

        PhoneNumberjLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberjLabel4.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberjLabel4.setText("User Name");

        addUserNamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserNamejTextField1ActionPerformed(evt);
            }
        });

        PhoneNumberjLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumberjLabel5.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumberjLabel5.setText("Password");

        addPasswordjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordjTextField1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        NamejLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamejLabel4.setForeground(new java.awt.Color(255, 255, 255));
        NamejLabel4.setText("Researcher Id");

        IdjLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IdjLabel1.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressjLabel)
                            .addComponent(AddressjLabel2)
                            .addComponent(AgejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberjLabel)
                            .addComponent(PhoneNumberjLabel1)
                            .addComponent(PhoneNumberjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NamejLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addUserNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zipCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressjLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AddressjLabel3)
                                            .addComponent(AgejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(AddressjLabel5))
                                        .addGap(49, 49, 49))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PhoneNumberjLabel3)
                                            .addComponent(NamejLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PhoneNumberjLabel4)
                                            .addComponent(PhoneNumberjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addUserNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumberjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addAgejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zipCodejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addPasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jButton3)))
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(NamejLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamejLabel4)
                            .addComponent(IdjLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamejLabel3)
                            .addComponent(addNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAgejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel3)
                            .addComponent(AddressjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel4)
                            .addComponent(zipCodejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel5)
                            .addComponent(CityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumberjLabel3)
                            .addComponent(phoneNumberjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumberjLabel4)
                            .addComponent(addUserNamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumberjLabel5)
                            .addComponent(addPasswordjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IdjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NamejLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NamejLabel1)
                            .addComponent(addNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgejLabel)
                            .addComponent(addAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel)
                            .addComponent(AddressjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel1)
                            .addComponent(zipCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressjLabel2)
                            .addComponent(CityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumberjLabel)
                            .addComponent(phoneNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumberjLabel1)
                            .addComponent(addUserNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneNumberjLabel2)
                            .addComponent(addPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Researcher To Be Deleted");

        jLabel4.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Organ Bank Admin ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedRowIndex= jTable1.getSelectedRow();
        
       if(selectedRowIndex<0){            
            return;
       }
       DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
       IdjLabel.setText(model.getValueAt(selectedRowIndex,0).toString());
        addNamejTextField.setText(model.getValueAt(selectedRowIndex,1).toString());
        addAgejTextField.setText(model.getValueAt(selectedRowIndex,2).toString());
        AddressjTextField.setText(model.getValueAt(selectedRowIndex,3).toString());
        zipCodejTextField.setText(model.getValueAt(selectedRowIndex,4).toString());
        CityjTextField.setText(model.getValueAt(selectedRowIndex,5).toString());
        phoneNumberjTextField.setText(model.getValueAt(selectedRowIndex,6).toString());
        IdjLabel1.setText(model.getValueAt(selectedRowIndex,0).toString());
        addNamejTextField1.setText(model.getValueAt(selectedRowIndex,1).toString());
        addAgejTextField1.setText(model.getValueAt(selectedRowIndex,2).toString());
        AddressjTextField1.setText(model.getValueAt(selectedRowIndex,3).toString());
        zipCodejTextField1.setText(model.getValueAt(selectedRowIndex,4).toString());
        CityjTextField1.setText(model.getValueAt(selectedRowIndex,5).toString());
        phoneNumberjTextField1.setText(model.getValueAt(selectedRowIndex,6).toString());
        OrganBankResearcherDirectory dir = new OrganBankResearcherDirectory();
        String[] arr = dir.getCredentials(model.getValueAt(selectedRowIndex,9).toString());
        addUserNamejTextField.setText(arr[0]);
        addPasswordjTextField.setText(arr[1]);
        addUserNamejTextField1.setText(arr[0]);
        addPasswordjTextField1.setText(arr[1]);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    CreateOrganResearcherJPanel ResearcherPanel = new CreateOrganResearcherJPanel(container, business, DonorAdminID);
        container.add("donorCreatePanel", ResearcherPanel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        OrganBankResearcher researcher = new OrganBankResearcher();
        OrganBankResearcherDirectory directory = new OrganBankResearcherDirectory();
        int selectedRowIndex= jTable1.getSelectedRow();
        researcher.setName(addNamejTextField.getText());
        researcher.setAge(addAgejTextField.getText());
        researcher.setAddress(AddressjTextField.getText());
        researcher.setZipCode(zipCodejTextField.getText());
        researcher.setCity(CityjTextField.getText());
        researcher.setPhoneNumber(phoneNumberjTextField.getText());
        researcher.setId(IdjLabel.getText());
        researcher.setForeignKey(jTable1.getValueAt(selectedRowIndex,9).toString());
        if( addUserNamejTextField.getText().isEmpty() || addPasswordjTextField.getText().isEmpty() || researcher.getName().isEmpty() ||
            researcher.getAge().isEmpty() || researcher.getAddress().isEmpty() || researcher.getZipCode().isEmpty()|| researcher.getCity().isEmpty()||researcher.getPhoneNumber().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Kindly Enter all the required fields!");
        }   else if (!business.validateMobileNo(researcher.getPhoneNumber())) {
            JOptionPane.showMessageDialog(null, "Kindly enter a Valid Contact Number.");
        } 
        else
        {
        //researcher.setForeignKey();
       directory.updateOrganResearcher(researcher, addUserNamejTextField.getText(),addPasswordjTextField.getText());
        IdjLabel.setText("");
        addNamejTextField.setText("");
        addAgejTextField.setText("");
        AddressjTextField.setText("");
        zipCodejTextField.setText("");
        CityjTextField.setText("");
        phoneNumberjTextField.setText("");
        IdjLabel1.setText("");
        addNamejTextField1.setText("");
        addAgejTextField1.setText("");
        AddressjTextField1.setText("");
        zipCodejTextField1.setText("");
        CityjTextField1.setText("");
        phoneNumberjTextField1.setText("");
        addUserNamejTextField.setText("");
        addPasswordjTextField.setText("");
        addUserNamejTextField1.setText("");
        addPasswordjTextField1.setText("");
        initalizeOrganBank(DonorAdminID);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void zipCodejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodejTextFieldActionPerformed

    private void addPasswordjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordjTextFieldActionPerformed

    private void AddressjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextFieldActionPerformed

    private void CityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityjTextFieldActionPerformed

    private void addUserNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserNamejTextFieldActionPerformed

    private void AddressjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressjTextField1ActionPerformed

    private void zipCodejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodejTextField1ActionPerformed

    private void CityjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityjTextField1ActionPerformed

    private void addUserNamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserNamejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserNamejTextField1ActionPerformed

    private void addPasswordjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPasswordjTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jdbcConnection jdbconnection = new jdbcConnection();
            Connection conn = jdbconnection.connect();
      try {
            
            String sql = "delete from organBlood.organResearcherTable where id=?";
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setString(1,IdjLabel1.getText());
            statement.executeUpdate();
            int selectedRowIndex= jTable1.getSelectedRow();
            if(selectedRowIndex>0)
            { DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
            deleteperson(model.getValueAt(selectedRowIndex,9).toString());
            initalizeOrganBank(DonorAdminID); 
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrganBankAdminJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
      finally
      { jdbconnection.disConnnect(conn);
         IdjLabel.setText("");
        addNamejTextField.setText("");
        addAgejTextField.setText("");
        AddressjTextField.setText("");
        zipCodejTextField.setText("");
        CityjTextField.setText("");
        phoneNumberjTextField.setText("");
        IdjLabel1.setText("");
        addNamejTextField1.setText("");
        addAgejTextField1.setText("");
        AddressjTextField1.setText("");
        zipCodejTextField1.setText("");
        CityjTextField1.setText("");
        phoneNumberjTextField1.setText("");
        addUserNamejTextField.setText("");
        addPasswordjTextField.setText("");
        addUserNamejTextField1.setText("");
        addPasswordjTextField1.setText("");
      }
    }//GEN-LAST:event_jButton3ActionPerformed
public void initalizeOrganBank(String insuranceNumber)
{ jdbcConnection jdbconnection = new jdbcConnection();
 Connection conn = jdbconnection.connect();
        try {
            ResultSet rs = null;
            
            String sql = "SELECT * FROM organBankTable where organBankId=?";
            
            PreparedStatement statement = conn.prepareStatement(sql);
            
            statement.setString(1,insuranceNumber);
            
            //System.out.print(jTextField3.getText());

            rs = statement.executeQuery();
            while(rs.next())
            {
            
                    }
//            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
        } catch (SQLException ex) {
            Logger.getLogger(HospitalManagementJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally
        {
         jdbconnection.disConnnect(conn);
        }
        
}
public boolean deleteperson(String personId)
{ jdbcConnection jdbconnection = new jdbcConnection();
  Connection conn = jdbconnection.connect();
  boolean val= false;
  try
  {
        String sql = "delete from organBlood.personTable where insuranceNumber=?";
        PreparedStatement statement = conn.prepareStatement(sql);
        statement.setString(1,personId);
        statement.executeUpdate();
        val=true;
  }
  catch(SQLException ex)
      {
         Logger.getLogger(HospitalManagementJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
      
  finally
  {jdbconnection.disConnnect(conn);
          }
  return val;

}

public void setempty()
{        IdjLabel.setText("");
        addNamejTextField.setText("");
        addAgejTextField.setText("");
        AddressjTextField.setText("");
        zipCodejTextField.setText("");
        CityjTextField.setText("");
        phoneNumberjTextField.setText("");
        IdjLabel1.setText("");
        addNamejTextField1.setText("");
        addAgejTextField1.setText("");
        AddressjTextField1.setText("");
        zipCodejTextField1.setText("");
        CityjTextField1.setText("");
        phoneNumberjTextField1.setText("");
        addUserNamejTextField.setText("");
        addPasswordjTextField.setText("");
        addUserNamejTextField1.setText("");
        addPasswordjTextField1.setText("");

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressjLabel;
    private javax.swing.JLabel AddressjLabel1;
    private javax.swing.JLabel AddressjLabel2;
    private javax.swing.JLabel AddressjLabel3;
    private javax.swing.JLabel AddressjLabel4;
    private javax.swing.JLabel AddressjLabel5;
    private javax.swing.JTextField AddressjTextField;
    private javax.swing.JTextField AddressjTextField1;
    private javax.swing.JLabel AgejLabel;
    private javax.swing.JLabel AgejLabel1;
    private javax.swing.JTextField CityjTextField;
    private javax.swing.JTextField CityjTextField1;
    private javax.swing.JLabel IdjLabel;
    private javax.swing.JLabel IdjLabel1;
    private javax.swing.JLabel NamejLabel1;
    private javax.swing.JLabel NamejLabel2;
    private javax.swing.JLabel NamejLabel3;
    private javax.swing.JLabel NamejLabel4;
    private javax.swing.JLabel PhoneNumberjLabel;
    private javax.swing.JLabel PhoneNumberjLabel1;
    private javax.swing.JLabel PhoneNumberjLabel2;
    private javax.swing.JLabel PhoneNumberjLabel3;
    private javax.swing.JLabel PhoneNumberjLabel4;
    private javax.swing.JLabel PhoneNumberjLabel5;
    private javax.swing.JTextField addAgejTextField;
    private javax.swing.JTextField addAgejTextField1;
    private javax.swing.JTextField addNamejTextField;
    private javax.swing.JTextField addNamejTextField1;
    private javax.swing.JTextField addPasswordjTextField;
    private javax.swing.JTextField addPasswordjTextField1;
    private javax.swing.JTextField addUserNamejTextField;
    private javax.swing.JTextField addUserNamejTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phoneNumberjTextField;
    private javax.swing.JTextField phoneNumberjTextField1;
    private javax.swing.JTextField zipCodejTextField;
    private javax.swing.JTextField zipCodejTextField1;
    // End of variables declaration//GEN-END:variables
}
